### ISSUE TITLE
dataInit()問題

### ISSUE THREAD

**Issue by Yo-Hsin** [ntuee-webprogramming/hack2-QAs#16]
想問一下dataInit()如果正確執行的話會顯示怎樣的畫面?
我目前是在mongodb重新開一個project，並照著preReadme去create database(hack2)和collection(post)，並把該cluster的connection複製貼到.env中
但從mongodb那邊打開卻沒有看到任何data
想問MONGO_URL這樣寫是對的嗎? 
MONGO_URL=mongodb+srv://name:password@post.30a7l.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
![image](https://user-images.githubusercontent.com/74882667/144951144-af5e540f-c53f-4f4e-8d3a-ba3a4540aaa1.png)

**Comment by ntuee-webprogramming** [comment]
呃，請自己試一下哦！這是考試的一部分。然後，把自己的 password 貼上來不太好吧？
