### ISSUE TITLE
cypress 不知道怎麼測試

### ISSUE THREAD

**Issue by hellohello77** [ntuee-webprogramming/hack2-QAs#18]
助教請問cypress要怎麼跑? 是不是要先裝什麼套件阿，我的電腦不認識"cypress"這個指令。另外問一下是用cypress open開嗎

**Comment by raywu0123** [comment]
要裝的套件都寫在 preREADME 了 (https://hackmd.io/@UTZnTlSqR46n46iMn1U_lQ/H1b03gV_d)
執行的指令已經幫你們寫好，只要執行 yarn test 就可以了 (https://hackmd.io/cIe2qNMsTy6mPUVyTkjtFQ?view#Running-Tests)
