### ISSUE TITLE
個人電腦問題

### ISSUE THREAD

**Issue by AliceDu2002** [ntuee-webprogramming/hack2-QAs#19]
如果是自己電腦當掉的情況想請問有補救辦法嗎？
他剛剛整個當掉現在還在重新開機
我怕連剛剛寫好的code都沒辦法push…

**Comment by ntuee-webprogramming** [comment]
希望你重開後就好了...

**Comment by AliceDu2002** [comment]
助教可能真的沒辦法…
他已經跳好幾次藍屏顯示無法修復了…

**Comment by ntuee-webprogramming** [comment]
請照相截圖作為證明，然後真的無法使用的話，請停止作答。等到你電腦修好後，再來找我們補考。記得到 myntu 請事假。

**Comment by AliceDu2002** [comment]
好，謝謝
