### ISSUE TITLE
hack2 爛掉了

### ISSUE THREAD

**Issue by JTKiew** [ntuee-webprogramming/hack2-QAs#2]
![image](https://user-images.githubusercontent.com/45333715/144949735-c49d64c7-6a83-4faf-aef7-276d2b551437.png)

**Comment by andyh0913** [comment]
看起來可能是你電腦的硬碟空間不夠了，你看能不能清一點空間出來

**Comment by ntuee-webprogramming** [comment]
這應該是你自己電腦系統的問題，請 Google 尋找解答
