### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by warronyiang15** [ntuee-webprogramming/hack2-QAs#22]
Hi, 

![Screenshot 2021-12-07 at 10 13 26 AM](https://user-images.githubusercontent.com/65525835/144953628-55463c72-48d1-41cc-919b-bb130d90ba7f.png)

在server.js 加上 app.use(cors()) 也沒效果qq
* 已經yarn add cors + npm install cors

**Comment by ntuee-webprogramming** [comment]
你之前的 homework 可以 work 嗎？

**Comment by warronyiang15** [comment]
可以喔

**Comment by warronyiang15** [comment]
目前其他功能貌似沒問題 但不知道為什麼只有post newpost 的部分有問題

**Comment by ntuee-webprogramming** [comment]
那你自己再檢查一下
