### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by jasperchan5** [ntuee-webprogramming/hack2-QAs#23]
您好，我於測試todo 2時，前後端路徑都有按照規定打，但網頁上一直顯示network error。
請問這是能夠自行解決的嗎?

**Comment by ntuee-webprogramming** [comment]
Error message 是什麼呢？

**Comment by jasperchan5** [comment]
Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:117)

**Comment by ntuee-webprogramming** [comment]
看來是你 routing 寫錯
