### ISSUE TITLE
跑了yarn start跑步起來，連yarn server也一起出錯

### ISSUE THREAD

**Issue by HenningY** [ntuee-webprogramming/hack2-QAs#28]
<img width="548" alt="螢幕擷取畫面 2021-12-07 103237" src="https://user-images.githubusercontent.com/79901008/144955481-90ebd313-c5a4-4480-81c7-02773433f60c.png">

**Comment by ntuee-webprogramming** [comment]
是不是沒有裝 nodemon...?

**Comment by HenningY** [comment]
解決了 謝謝老師
