### ISSUE TITLE
3-1沒過 3-2有過

### ISSUE THREAD

**Issue by chiluen** [ntuee-webprogramming/hack2-QAs#33]
助教你好，想請問一下我用cypress測試時3-1沒過，但3-2有過，並且我的網頁在點選文章時確實會跑出文章內容(但每一次跑出文章內容的一瞬間都會跑出"Post not found"，然後就會跑出文章內容)，想請問這是因為我還沒寫後面題目的問題嘛，因為我想說都已經呈獻出文章了，不知道哪裡出了問題

**Comment by ntuee-webprogramming** [comment]
可以參考一下 cypress/integration/public.spec.js, 自行 figure out 問題在哪裡

**Comment by chiluen** [comment]
好的，已參考並解決，謝謝!

**Comment by jimshao1999** [comment]
你好我也有遇到這個問題，請問是原本就算是考試時自己應該要處理的嗎
