### ISSUE TITLE
寫後端posdDetail的時候 沒辦法用curl去測

### ISSUE THREAD

**Issue by YuKai0928** [ntuee-webprogramming/hack2-QAs#35]
以下是我的curl指令 參考講義的
curl -X GET http://localhost:4000/api/postDetail -d '{"postID": 3}' -H "Content-Type:application/json"
的確可以呼叫到router 會被處理到 但就是無法拿到curl -d的東西

**Comment by ntuee-webprogramming** [comment]
GET 為什麼有 -d...

**Comment by YuKai0928** [comment]
那請問我該怎麼把pid傳給router qq
readme寫GET沒錯qq
