### ISSUE TITLE
require and import issues in node.js

### ISSUE THREAD

**Issue by warronyiang15** [ntuee-webprogramming/hack2-QAs#37]
Hi ,

由於助教提供的ref code 都是用import，但在本端會報錯，所以改用require來import，請問這樣會影響分數嗎？

***改成require後程式能正常跑*
![Screenshot 2021-12-07 at 10 56 09 AM](https://user-images.githubusercontent.com/65525835/144957836-29332433-05e7-4e8f-8a56-2e101ca2f9ec.png)
**

**Comment by ntuee-webprogramming** [comment]
你有使用 babel 嗎？

**Comment by warronyiang15** [comment]
有 但還是會報錯 也試過google找問題，是說要在package.json 加上 type : module, 但是還是會報錯，之前作業也是這樣，所以一直都是用require

**Comment by ntuee-webprogramming** [comment]
這是你的 babel 沒有使用正確的關係。確定你有寫 .babelrc 嗎？

Anyway, 這應該不是問題，我們會在自己的環境幫你測。

**Comment by warronyiang15** [comment]
謝謝助教，教授 ，麻煩你們了 :D
