### ISSUE TITLE
執行yarn start出現問題

### ISSUE THREAD

**Issue by chiluen** [ntuee-webprogramming/hack2-QAs#4]
我在執行yarn start/server 時 會出現internal watch failed: ENOSPC: SYStem limit for number of file watchers reached  查了一下網路不知道怎麼解決  已按照readme安裝所有東西了

**Comment by raywu0123** [comment]
這個是系統參數設定的問題，請問有試過這邊的解法了嗎?
https://stackoverflow.com/questions/55763428/react-native-error-enospc-system-limit-for-number-of-file-watchers-reached

**Comment by chiluen** [comment]
已解決  謝謝!
