### ISSUE TITLE
Cypress 5-1 expected [ Array(4) ] to have a length of 5 but got 4

### ISSUE THREAD

**Issue by Brian-Konr** [ntuee-webprogramming/hack2-QAs#50]
想請問題目 5 也需要回傳 response.body.data 嗎？因為我看 readme 只需要回傳 message？

**Comment by ntuee-webprogramming** [comment]
是在問 error message 嗎？

**Comment by andyh0913** [comment]
> 想請問題目 5 也需要回傳 response.body.data 嗎？因為我看 readme 只需要回傳 message？

這個 error 應該是有其他功能寫錯導致的，詳情可以參考 public.spec.js
