### ISSUE TITLE
yarn server 出問題

### ISSUE THREAD

**Issue by JTKiew** [ntuee-webprogramming/hack2-QAs#6]
![image](https://user-images.githubusercontent.com/45333715/144950243-dc17bb0f-6730-4d6d-9d4c-20b26e48a7a6.png)

**Comment by ntuee-webprogramming** [comment]
那就裝一下 nodemon 啊！建議可以裝載 global.

我們會用自己的環境來測，所以 no worry.

**Comment by JTKiew** [comment]
好的 謝謝教授
