### ISSUE TITLE
datainit 在繳交程式時需不需要加上

### ISSUE THREAD

**Issue by chiluen** [ntuee-webprogramming/hack2-QAs#60]
助教你好，我目前若加上database連上時，datainit那兩行，用cypress時第1題到第4題都對，但沒加上去後我自己新增一些data前面的測資就會錯，因此我想請問再提交程式碼時要加上
if (process.env.MODE === 'EXAM')
    dataInit()
這兩行嘛，謝謝

**Comment by ntuee-webprogramming** [comment]
請按照題目說明，uncomment 後再執行測試。然後這個 issue 前面也有人問過了，請先爬文
