### ISSUE TITLE
mongodb database issues

### ISSUE THREAD

**Issue by warronyiang15** [ntuee-webprogramming/hack2-QAs#66]
Hi,

我發現在程式使用的database沒有指定位置，而只是指定collection為post，造成在我的mongodb 中hack2 database裡的post沒有被使用，反而是另一個database中會自行生成post來使用，雖然對整體程式沒有任何影響，但是詢問若助教批改時會指定database的位置嗎？
![Screenshot 2021-12-07 at 11 55 30 AM](https://user-images.githubusercontent.com/65525835/144963407-034d3aa3-4a79-469f-959b-f2df3f484111.png)
<img width="1178" alt="Screenshot 2021-12-07 at 11 55 58 AM" src="https://user-images.githubusercontent.com/65525835/144963480-c1884878-05cf-4d0b-86e6-e9b26745ded3.png">

<img width="1169" alt="Screenshot 2021-12-07 at 11 56 11 AM" src="https://user-images.githubusercontent.com/65525835/144963494-0ea372d5-cba5-43c1-a495-e415913e50dd.png">

**Comment by ntuee-webprogramming** [comment]
請不用擔心，我們會使用自己的 db 批改

**Comment by warronyiang15** [comment]
謝謝助教and教授！
