### ISSUE TITLE
cypress每次跑都出現不同結果

### ISSUE THREAD

**Issue by vwvwMM** [ntuee-webprogramming/hack2-QAs#67]
我的cypress就算我沒有改任何地方，連跑兩次，竟然會出現上次沒錯的這次錯了，這是甚麼問題呢？

**Comment by ntuee-webprogramming** [comment]
這個可能要自己檢查有沒有什麼地方寫錯了...

**Comment by vwvwMM** [comment]
我中間有在app中做了一些操作，是不是這個原因呢?
我在app上的操作明明都沒有出錯，但cypress就一直沒過...

**Comment by vwvwMM** [comment]
尤其是4-2那邊有時對有時錯的，感覺300好像不太夠?

**Comment by ntuee-webprogramming** [comment]
批改時是用我們自己的環境與電腦去改，no worry.
