### ISSUE TITLE
Data init 無動靜

### ISSUE THREAD

**Issue by b09901039** [ntuee-webprogramming/hack2-QAs#8]
<img width="224" alt="image" src="https://user-images.githubusercontent.com/91512287/144950238-d7fad963-5678-4f9f-8d77-0622ea3e460b.png">

如題

**Comment by ntuee-webprogramming** [comment]
你有 .env 嗎？

**Comment by b09901039** [comment]
> 你有 .env 嗎？

.env .env.default 都有

**Comment by clins210** [comment]
同問

**Comment by ntuee-webprogramming** [comment]
你有檢查看看 DB 有沒有資料寫進去嗎？前端本來就不會有動靜 (除非你們寫完了)

**Comment by b09901039** [comment]
建議把if 直接去掉 (懶的處理
push的時候 記得把data init拿掉就好了

**Comment by clins210** [comment]
我的後端沒有print在裡面寫要印的提示字

**Comment by clins210** [comment]
[已解決] 是網路問題-.-
